from string import Template

CODE_DESC_TASK: str = """
You are an AI assistant to a senior data scientist, your job is to explain to a senior data scientist each line of code in detail. 
Your answers should help them understand code better.
"""

EXPLANATION: str = """
Explanation: This code imports the OpenAI class from the openai module and the OPENAI_API_KEY from the wolf_assistant.config.tokens module. It then creates an instance of the OpenAI class called client with the API key provided.
The generate_response function takes a text input, sends it to the OpenAI chat model "gpt-3.5-turbo", and returns the response generated by the model. The max_tokens parameter specifies the maximum number of tokens the model should generate, and the temperature parameter controls the randomness of the generated response.
The generate_transcription function takes audio data in bytes, sends it to the OpenAI audio transcription model "whisper-1", and returns the transcribed text from the audio. The audio_bytes list specifies which variables and functions should be exported when this module is imported by another module. In this case, it includes client, generate_response, and generate_transcription.
"""

TEXT_EXAMPLE: str = """
Here is an example: 
Code: 
```
from openai import OpenAI
from wolf_assistant.config.tokens import OPENAI_API_KEY

client = OpenAI(
    api_key=OPENAI_API_KEY,)

def generate_response(text):
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",        
        messages=[{"role": "user", "content": text}],        
        max_tokens=1024,        
        temperature=0.5
    )
    print(response.choices[0].message.content.strip())
    return response.choices[0].message.content.strip()

def generate_transcription(audio_bytes):
    transcription = client.audio.transcriptions.create(model="whisper-1", file=("audio.oga", audio_bytes, "audio/ogg"))
    return transcription.text.strip()
```

""" + EXPLANATION


CODE_DESC_BODY: Template = Template("""
Code:
```
$input_text
```
Explanation: 
""")
